export const MAIN_API = "http://localhost:3002/api/";
export const MAIL_API = "http://localhost:3002/api/v1/mailer/";

export const API_STATUS = {
  SERVICE_ERROR: "WEB_SERVICE_REQUEST_ERROR",
  SERVICE_IDLE: "WEB_SERVICE_REQUEST_IDLE",
  SERVICE_PENDING: "WEB_SERVICE_REQUEST_PENDING",
  SERVICE_SUCCESS: "WEB_SERVICE_REQUEST_SUCCESS",
};
